# Generated by Django 3.2.10 on 2021-12-16 05:57

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='home.homepage'),
        ),
    ]
