# Generated by Django 3.2.10 on 2021-12-16 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211216_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageGalleryImage',
        ),
    ]
